---
title: 'The Transfer Market Madness: Determinants and Predictions of Football Player Transfer Fees'
author: Simon Schölzel
date: '2019-12-20'
categories:
  - ggplot2
  - tidymodels
  - rvest
  - RSelenium
  - leaps
  - glmnet
tags:
  - ggplot2
  - tidymodels
  - rvest
  - RSelenium
  - leaps
  - glmnet
subtitle: ''
summary: 'A machine learning project from my time at CBS on predictive modelling of soccer player transfer fees realized in R. `r emo::ji("soccer_ball")`'
lastmod: '2019-12-19T23:23:00+02:00'
image:
  caption: '[Photo by Markus Spiske on Pexels](https://www.pexels.com/de-de/foto/himmel-sonnenuntergang-feld-sonnenaufgang-114296/)'
  focal_point: ''
  preview_only: false
projects: []
---

### Abstract

In the recent years, excessive transfer fees for football players have turned the European transfer market upside down – a development coined as the ‘transfer market madness’ in this paper. Predicting those fees is assumed to be of great interest to researchers, policy makers, managers and the public alike. This paper addresses the issue by discussing the following four research questions: (1) What are the important value drivers that determine transfer fees in the European football market? (2) Is there a significant influence of a player’s popularity on transfer fees? (3) Which model for estimating football transfer fees performs best in terms of predictive accuracy? (4) Where is the transfer market madness heading to?

For this purpose, five predictive modelling techniques from the regression family are proposed: linear, stepwise forward, Ridge, Lasso and polynomial regression. The models are trained on a rich data set of 2,634 transfers observed during the 2013-2019 period which is scraped from transfermarkt.de, kaggle.com and Wikipedia. The empirical results reveal numerous important predictors for the transfer fee and especially indicate that the median player transfer incorporates a €1,06 million price premium that accounts for a player’s popularity. Moreover, the quadratic regression model yields the overall best predictive accuracy with the 1-standard error-rule Lasso model being the least prone to overfitting. Finally, the latter is deployed and evaluated on four currently rumoured transfers. The generated predictions are not only remarkably close to what is hypothesised by the media but also suggest that the transfer market madness is there to stay.

Eventually, the paper advocates the use of novel predictors and consideration of non-linear relationships in future research. From a practical perspective, this study develops a tool that can aid managers and agents in terms of decision-making. In addition, concerns regarding the ethical and psychological implications of the transfer market development are raised leading to the question: When will the excessive costs become unbearable for the average team as well as the players and how will it shape the competitive equilibrium in the future of football?

__________

**R code** available on [Github](https://github.com/simonschoe/project_player_transfers).

**Project paper** available under this [Link](/files/football-player-transfers.pdf).
